name: test3
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  #fiarbaseのパッケージ？
  firebase_core: ^2.13.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.3
  line_icons: ^2.0.1
  #flutter_launcher_icons: ^0.13.1
  lottie: ^2.3.2
  google_fonts: ^4.0.4
  #google_fonts: ^5.1.0
  #flare_flutter: ^3.0.0-nullsafety.0
  


dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

  

flutter:
    assets:
    - assets/
    - assets/googlefont/

uses-material-design: true

  