name: test3
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  #fiarbaseのパッケージ？z
  firebase_core: ^2.14.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.3
  line_icons: ^2.0.3
  lottie: ^2.3.2
  google_fonts: ^4.0.4
  persistent_bottom_nav_bar: ^4.0.2
  flutter_native_splash: ^2.2.19
  image_picker: ^1.0.1
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  cached_network_image: ^3.2.3
  provider: ^5.0.0
  printing: ^5.10.4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  like_button: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  animated_text_kit: ^4.2.2

  

 
dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

  

flutter:
    assets:
    - lib/src/img/
    - assets/
    - assets/googlefont/

uses-material-design: true


flutter_native_splash:
  image: 'lib/src/img/s.png' 
  color: "#FFFFFF"


  #  追加
flutter_icons:       
  android: true
  ios: true
  image_path: "lib/src/img/s.png"